trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: curl -o- -L https://yarnpkg.com/install.sh | bash
  displayName: 'Install yarn'

- script: yarn
  displayName: 'Install dependencies'

- script: yarn build
  displayName: 'Build'
