name: Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Github Package Registry
      env:
        GITHUB_AUTH_USER: ${{ secrets.GITHUB_AUTH_USER }}
        GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: docker login docker.pkg.github.com -u $GITHUB_AUTH_USER -p $GITHUB_AUTH_TOKEN
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/tirr-c/ames-discord/ames-discord:git-$(git rev-parse --short @)
    - name: Push the Docker image
      run: docker push docker.pkg.github.com/tirr-c/ames-discord/ames-discord:git-$(git rev-parse --short @)
